(define wert1 8)
(define wert2 77)
(define wert3 3.14)
(define wert4 1+2i)
(define booleanwert #t)
(define zeichenkette "Hallo")
(define buchstabe #\A)
(define integerzahl (- wert1 wert2))
(define rationalzahl (/ wert1 wert2))
(define realzahl (+ wert2 wert3))
(define complexzahl (+ wert1 wert4))

(display booleanwert)
(display " ist Boolean?: ")
(display (boolean? booleanwert))
(newline)

(display zeichenkette)
(display " ist String?: ")
(display (string? zeichenkette))
(newline)

(display buchstabe)
(display " ist Char?: ")
(display (char? buchstabe))
(newline)

(display integerzahl)
(display " ist Integer?: ")
(display (integer? integerzahl))
(newline)

(display rationalzahl)
(display " ist Rational?: ")
(display (rational? rationalzahl))
(newline)

(display realzahl)
(display " ist Real?: ")
(display (real? realzahl))
(newline)

(display complexzahl)
(display " ist Complex?: ")
(display (complex? complexzahl))
(newline)